[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
token_manager = "3xYxr5FqjM6y54PZrovqEkiYiHznS3WJWB8Lm9Bn4SGG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.testnet.sonic.game"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
